#!/bin/bash
# deploy_aws.sh
# Automates: terraform apply → generate hosts_aws.ini → run ansible
#
# Usage:
#   ./deploy_aws.sh          # full deploy (terraform + ansible)
#   ./deploy_aws.sh plan     # just show what terraform will create
#   ./deploy_aws.sh infra    # terraform only, no ansible
#   ./deploy_aws.sh ansible  # ansible only (reuse existing infra)
#   ./deploy_aws.sh destroy  # tear down everything
 
set -e
 
PROJECT_DIR="/home/user1/project1-onpremise"
TERRAFORM_DIR="$PROJECT_DIR/terraform"
INVENTORY="$PROJECT_DIR/inventory/hosts_aws.ini"
 
# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
 
log()  { echo -e "${GREEN}[$(date '+%H:%M:%S')] $1${NC}"; }
warn() { echo -e "${YELLOW}[$(date '+%H:%M:%S')] $1${NC}"; }
err()  { echo -e "${RED}[$(date '+%H:%M:%S')] $1${NC}"; }
 
# ── Functions ──────────────────────────────────────────────────────────
 
run_terraform() {
  log "Running terraform apply..."
  cd "$TERRAFORM_DIR"
  terraform apply -auto-approve
  log "Terraform apply complete"
}
 
generate_inventory() {
  log "Generating inventory/hosts_aws.ini from terraform outputs..."
  cd "$TERRAFORM_DIR"
 
  MGMT_IP=$(terraform output -raw mgmt_public_ip)
  ROCKY1_IP=$(terraform output -raw rocky1_private_ip)
  ROCKY2_IP=$(terraform output -raw rocky2_private_ip)
  UBUNTU1_IP=$(terraform output -raw ubuntu1_private_ip)
  ALB_DNS=$(terraform output -raw alb_dns_name)
 
  cat > "$INVENTORY" << EOF
# inventory/hosts_aws.ini
# Auto-generated by deploy_aws.sh on $(date)
# Terraform apply ID: $(terraform show -json | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('values',{}).get('root_module',{}).get('resources',[{}])[0].get('values',{}).get('id','unknown'))" 2>/dev/null || echo "unknown")
 
[mgmt]
${MGMT_IP} ansible_user=user1
 
[rocky]
${ROCKY1_IP} ansible_user=user1 ansible_ssh_common_args='-o ProxyJump=user1@${MGMT_IP} -o StrictHostKeyChecking=no'
${ROCKY2_IP} ansible_user=user1 ansible_ssh_common_args='-o ProxyJump=user1@${MGMT_IP} -o StrictHostKeyChecking=no'
 
[ubuntu]
${UBUNTU1_IP} ansible_user=user1 ansible_ssh_common_args='-o ProxyJump=user1@${MGMT_IP} -o StrictHostKeyChecking=no'
 
[all:vars]
ansible_ssh_private_key_file=/home/user1/.ssh/teamproj01ansiblekey.pem
ansible_python_interpreter=/usr/bin/python3
db_host=${UBUNTU1_IP}
EOF
 
  log "Inventory written to $INVENTORY"
  echo ""
  warn "=== AWS Infrastructure Ready ==="
  echo "  Mgmt (public):   $MGMT_IP"
  echo "  Rocky1 (private): $ROCKY1_IP"
  echo "  Rocky2 (private): $ROCKY2_IP"
  echo "  Ubuntu1 (private): $UBUNTU1_IP"
  echo "  ALB URL:          http://$ALB_DNS"
  echo ""
}
 
wait_for_ssh() {
  log "Waiting for mgmt SSH to be ready..."
  cd "$TERRAFORM_DIR"
  MGMT_IP=$(terraform output -raw mgmt_public_ip)
 
  for i in $(seq 1 30); do
    if ssh -i ~/.ssh/teamproj01ansiblekey.pem \
         -o ConnectTimeout=5 \
         -o StrictHostKeyChecking=no \
         user1@"$MGMT_IP" "echo ok" 2>/dev/null | grep -q ok; then
      log "SSH ready on mgmt ($MGMT_IP)"
      return 0
    fi
    warn "Waiting for SSH... attempt $i/30"
    sleep 10
  done
 
  err "SSH not ready after 5 minutes. Check security group rules."
  exit 1
}
 
run_ansible() {
  log "Running ansible-playbook site_aws.yml..."
  cd "$PROJECT_DIR"
  ansible-playbook playbooks/site_aws.yml -i "$INVENTORY"
  log "Ansible complete"
}
 
run_destroy() {
  warn "Destroying all AWS infrastructure..."
  cd "$TERRAFORM_DIR"
  terraform destroy -auto-approve
  log "All resources destroyed"
 
  # Clear the inventory file so stale IPs don't cause confusion
  cat > "$INVENTORY" << EOF
# inventory/hosts_aws.ini
# Infrastructure destroyed on $(date)
# Run ./deploy_aws.sh to recreate
EOF
  log "Inventory cleared"
}
 
# ── Main ───────────────────────────────────────────────────────────────
 
case "${1:-deploy}" in
  plan)
    log "Running terraform plan..."
    cd "$TERRAFORM_DIR"
    terraform plan
    ;;
  infra)
    run_terraform
    generate_inventory
    wait_for_ssh
    log "Infrastructure ready. Run './deploy_aws.sh ansible' to configure."
    ;;
  ansible)
    generate_inventory
    run_ansible
    ;;
  destroy)
    run_destroy
    ;;
  deploy|"")
    run_terraform
    generate_inventory
    wait_for_ssh
    run_ansible
    cd "$TERRAFORM_DIR"
    ALB_DNS=$(terraform output -raw alb_dns_name)
    log "=== DEPLOYMENT COMPLETE ==="
    log "App URL: http://$ALB_DNS/health"
    log "Grafana: http://$(terraform output -raw mgmt_public_ip):3000"
    ;;
  *)
    echo "Usage: $0 [deploy|plan|infra|ansible|destroy]"
    exit 1
    ;;
esac