# ~/project/inventory/hosts.ini

[mgmt]
172.16.1.150 ansible_connection=local   # mgmt는 자기 자신이므로 local

[rocky]
172.16.1.151 ansible_user=user1
172.16.1.152 ansible_user=user1

[ubuntu]
172.16.1.153 ansible_user=user1

[all:vars]
ansible_ssh_private_key_file=~/.ssh/project.pem
ansible_python_interpreter=/usr/bin/python3
