########################################################################
# outputs.tf
########################################################################

output "mgmt_public_ip" {
  description = "Public IP of the mgmt/bastion node."
  value       = aws_instance.mgmt.public_ip
}

output "mgmt_instance_id" {
  description = "EC2 instance ID of mgmt."
  value       = aws_instance.mgmt.id
}

output "rocky1_private_ip" {
  description = "Private IP of rocky1."
  value       = aws_instance.rocky1.private_ip
}

output "rocky2_private_ip" {
  description = "Private IP of rocky2."
  value       = aws_instance.rocky2.private_ip
}

output "ubuntu1_private_ip" {
  description = "Private IP of ubuntu1 (PostgreSQL)."
  value       = aws_instance.ubuntu1.private_ip
}

output "alb_dns_name" {
  description = "Public DNS of the Application Load Balancer."
  value       = aws_lb.alb.dns_name
}

output "alb_zone_id" {
  description = "ALB hosted zone ID for Route53 alias record."
  value       = aws_lb.alb.zone_id
}

# ── Ready-to-use Ansible inventory ────────────────────────────────────
# Private instances are in private subnets — access via mgmt as jump host

output "ansible_inventory" {
  description = "Ready-to-paste content for inventory/hosts_aws.ini"
  value = <<-INI
    # inventory/hosts_aws.ini — generated by Terraform
    # Usage: ansible-playbook playbooks/site_aws.yml -i inventory/hosts_aws.ini

    [mgmt]
    ${aws_instance.mgmt.public_ip} ansible_user=user1

    [rocky]
    ${aws_instance.rocky1.private_ip} ansible_user=user1 ansible_ssh_common_args='-o ProxyJump=user1@${aws_instance.mgmt.public_ip} -o StrictHostKeyChecking=no'
    ${aws_instance.rocky2.private_ip} ansible_user=user1 ansible_ssh_common_args='-o ProxyJump=user1@${aws_instance.mgmt.public_ip} -o StrictHostKeyChecking=no'

    [ubuntu]
    ${aws_instance.ubuntu1.private_ip} ansible_user=user1 ansible_ssh_common_args='-o ProxyJump=user1@${aws_instance.mgmt.public_ip} -o StrictHostKeyChecking=no'

    [all:vars]
    ansible_ssh_private_key_file=/home/user1/.ssh/teamproj01ansiblekey.pem
    ansible_python_interpreter=/usr/bin/python3
    db_host=${aws_instance.ubuntu1.private_ip}
  INI
}

# ── Prometheus scrape targets ─────────────────────────────────────────

output "prometheus_scrape_targets" {
  description = "AWS IPs to update in monitoring/prometheus.yml"
  value = {
    mgmt           = "${aws_instance.mgmt.public_ip}:9100"
    rocky1         = "${aws_instance.rocky1.private_ip}:9100"
    rocky2         = "${aws_instance.rocky2.private_ip}:9100"
    ubuntu1        = "${aws_instance.ubuntu1.private_ip}:9100"
    fastapi_rocky1 = "${aws_instance.rocky1.private_ip}:8000"
    fastapi_rocky2 = "${aws_instance.rocky2.private_ip}:8000"
  }
}
