########################################################################
# outputs.tf
########################################################################

output "mgmt_public_ip" {
  description = "Public IP of the mgmt/bastion node."
  value = aws_instance.mgmt.public_ip
}

output "mgmt_instance_id" {
  description = "EC2 instance ID of mgmt."
  value = aws_instance.mgmt.id
}

output "rocky1_private_ip" {
  description = "Private IP of rocky1."
  value = aws_instance.rocky1.private_ip
}

output "rocky2_private_ip" {
  description = "Private IP of rocky2."
  value = aws_instance.rocky2.private_ip
}

output "ubuntu1_private_ip" {
  description = "Private IP of ubuntu1 (PostgreSQL)."
  value = aws_instance.ubuntu1.private_ip
}

output "alb_dns_name" {
  description = "ALB public DNS — open this in your browser."
  value       = aws_lb.alb.dns_name
}

output "alb_zone_id" {
  description = "ALB hosted zone ID for Route53 alias record."
  value = aws_lb.alb.zone_id
}

output "cloudwatch_dashboard_url" {
  description = "Direct URL to the CloudWatch dashboard."
  value       = "https://${var.aws_region}.console.aws.amazon.com/cloudwatch/home?region=${var.aws_region}#dashboards:name=${aws_cloudwatch_dashboard.main.dashboard_name}"
}

output "sns_topic_arn" {
  description = "SNS topic ARN for CloudWatch alarms."
  value       = aws_sns_topic.alerts.arn
}

# ── Ready-to-use Ansible inventory ────────────────────────────────────

output "ansible_inventory" {
  description = "Paste this into inventory/hosts_aws.ini"
  value = <<-INI
    # inventory/hosts_aws.ini — generated by Terraform
    [mgmt]
    ${aws_instance.mgmt.public_ip} ansible_user=user1

    [rocky]
    ${aws_instance.rocky1.private_ip} ansible_user=user1 ansible_ssh_common_args='-o ProxyJump=user1@${aws_instance.mgmt.public_ip} -o StrictHostKeyChecking=no'
    ${aws_instance.rocky2.private_ip} ansible_user=user1 ansible_ssh_common_args='-o ProxyJump=user1@${aws_instance.mgmt.public_ip} -o StrictHostKeyChecking=no'

    [ubuntu]
    ${aws_instance.ubuntu1.private_ip} ansible_user=user1 ansible_ssh_common_args='-o ProxyJump=user1@${aws_instance.mgmt.public_ip} -o StrictHostKeyChecking=no'

    [all:vars]
    ansible_ssh_private_key_file=/home/user1/.ssh/teamproj01ansiblekey.pem
    ansible_python_interpreter=/usr/bin/python3
    db_host=${aws_instance.ubuntu1.private_ip}
  INI
}


# ── Prometheus scrape targets ─────────────────────────────────────────

output "prometheus_scrape_targets" {
  description = "AWS IPs to update in monitoring/prometheus.yml"
  value = {
    mgmt           = "${aws_instance.mgmt.public_ip}:9100"
    rocky1         = "${aws_instance.rocky1.private_ip}:9100"
    rocky2         = "${aws_instance.rocky2.private_ip}:9100"
    ubuntu1        = "${aws_instance.ubuntu1.private_ip}:9100"
    fastapi_rocky1 = "${aws_instance.rocky1.private_ip}:8000"
    fastapi_rocky2 = "${aws_instance.rocky2.private_ip}:8000"
  }
}