# ~/project/monitoring/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] # Docker 버전
      # - targets: ['localhost:9093']    # # No-Docker 버전(같은 호스트에서 실행)

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-mgmt'
    static_configs:
      - targets: ['192.168.61.133:9100']
        labels: {instance: 'proj-mgmt'}

  - job_name: 'node-rocky1'
    static_configs:
      - targets: ['192.168.61.134:9100']
        labels: {instance: 'proj-rocky01'}

  - job_name: 'node-rocky2'
    static_configs:
      - targets: ['192.168.61.135:9100']
        labels: {instance: 'proj-rocky02'}

  - job_name: 'node-ubuntu1'
    static_configs:
      - targets: ['192.168.61.136:9100']
        labels: {instance: 'proj-ubuntu01'}

  - job_name: 'fastapi-rocky1'
    static_configs:
      - targets: ['192.168.61.134:8000']
        labels: {instance: 'proj-rocky01'}
    metrics_path: '/metrics'

  - job_name: 'fastapi-rocky2'
    static_configs:
      - targets: ['192.168.61.135:8000']
        labels: {instance: 'proj-rocky02'}
    metrics_path: '/metrics'
