# roles/monitoring/files/prometheus.yml
# On-prem version — binaries, not Docker
# ADDED: environment=onprem labels so alerts are distinguishable from AWS

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'onprem'
    location: 'vmware'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-mgmt'
    static_configs:
      - targets: ['192.168.61.133:9100']
        labels:
          instance: 'onprem-mgmt'
          environment: 'onprem'

  - job_name: 'node-rocky1'
    static_configs:
      - targets: ['192.168.61.134:9100']
        labels:
          instance: 'onprem-rocky1'
          environment: 'onprem'

  - job_name: 'node-rocky2'
    static_configs:
      - targets: ['192.168.61.135:9100']
        labels:
          instance: 'onprem-rocky2'
          environment: 'onprem'

  - job_name: 'node-ubuntu1'
    static_configs:
      - targets: ['192.168.61.136:9100']
        labels:
          instance: 'onprem-ubuntu1'
          environment: 'onprem'

  - job_name: 'fastapi-rocky1'
    static_configs:
      - targets: ['192.168.61.134:8000']
        labels:
          instance: 'onprem-rocky1'
          environment: 'onprem'
    metrics_path: '/metrics'

  - job_name: 'fastapi-rocky2'
    static_configs:
      - targets: ['192.168.61.135:8000']
        labels:
          instance: 'onprem-rocky2'
          environment: 'onprem'
    metrics_path: '/metrics'